# Generated by Django 4.1.3 on 2022-12-31 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
