# Generated by Django 4.1.3 on 2022-12-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
