# Generated by Django 4.1.3 on 2022-12-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_basicmenu_img_coffeemenu_img_drinkmenu_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inarimenu',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
