# Generated by Django 4.1.3 on 2022-12-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='kind',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
