# Generated by Django 4.1.3 on 2022-12-31 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_menu_mainmenu_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainmenu',
            name='d',
        ),
    ]
