# Generated by Django 4.1.3 on 2022-12-31 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_remove_mainmenu_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicmenu',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='coffeemenu',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='drinkmenu',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='inarimenu',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='mainmenu',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='setmenu',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='sidemenu',
            name='kind',
        ),
    ]
