# Generated by Django 4.1.3 on 2022-12-31 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_remove_basicmenu_kind_remove_coffeemenu_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenu',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menu'),
        ),
    ]
