# Generated by Django 4.1.3 on 2022-12-31 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_drinkmenu_kind_sidemenu_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicmenu',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menu'),
        ),
        migrations.AddField(
            model_name='coffeemenu',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menu'),
        ),
        migrations.AddField(
            model_name='inarimenu',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menu'),
        ),
        migrations.AddField(
            model_name='setmenu',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menu'),
        ),
    ]
